import { GoogleGenAI, Modality } from '@google/genai';
import { logger } from '../utils/logger.js';
import { saveImage, timestampedName } from '../utils/fileUtils.js';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

/**
 * Generate an image using Gemini 2.0 Flash (experimental image generation).
 */
async function generateWithGemini(prompt, referenceBase64 = null) {
  const contents = [];

  if (referenceBase64) {
    contents.push({
      inlineData: { data: referenceBase64, mimeType: 'image/jpeg' },
    });
  }
  contents.push({ text: prompt });

  const response = await ai.models.generateContent({
    model: 'gemini-2.0-flash-exp-image-generation',
    contents,
    config: {
      responseModalities: [Modality.IMAGE, Modality.TEXT],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData?.mimeType?.startsWith('image/')) {
      return part.inlineData.data;
    }
  }
  throw new Error('No image in Gemini response');
}

/**
 * Generate an image using Imagen 3.
 */
async function generateWithImagen(prompt) {
  const response = await ai.models.generateImages({
    model: 'imagen-3.0-generate-002',
    prompt,
    config: {
      numberOfImages: 1,
      aspectRatio: '9:16',
    },
  });

  if (!response.generatedImages?.length) {
    throw new Error('No images generated by Imagen');
  }
  return response.generatedImages[0].image.imageBytes;
}

/**
 * Generate an image and save it to disk.
 * @param {string} prompt - Image generation prompt
 * @param {object} options
 * @param {string} [options.model='gemini'] - 'gemini' or 'imagen'
 * @param {string} [options.referenceBase64] - Reference image as base64
 * @param {string} [options.filename] - Output filename (auto-generated if omitted)
 * @returns {string} Saved file path
 */
export async function generateImage(prompt, options = {}) {
  const { model = 'gemini', referenceBase64 = null, filename } = options;

  logger.step(`Generating image with ${model}...`);
  logger.debug('Prompt:', prompt);

  let base64Data;

  if (model === 'imagen') {
    base64Data = await generateWithImagen(prompt);
  } else {
    base64Data = await generateWithGemini(prompt, referenceBase64);
  }

  const outName = filename || timestampedName('image', 'jpg');
  const filepath = saveImage(base64Data, outName);
  logger.success(`Image saved: ${filepath}`);
  return filepath;
}

/**
 * Generate multiple images from an array of prompts.
 * @param {Array<{prompt: string, referenceBase64?: string, filename?: string}>} items
 * @param {object} options
 * @returns {string[]} Array of saved file paths
 */
export async function generateImages(items, options = {}) {
  const results = [];
  for (let i = 0; i < items.length; i++) {
    const item = items[i];
    logger.section(`Image ${i + 1} / ${items.length}`);
    try {
      const filepath = await generateImage(item.prompt, {
        model: options.model || 'gemini',
        referenceBase64: item.referenceBase64 || null,
        filename: item.filename || `image_${String(i + 1).padStart(2, '0')}_${Date.now()}.jpg`,
      });
      results.push({ index: i, filepath, prompt: item.prompt, success: true });
    } catch (err) {
      logger.error(`Image ${i + 1} failed: ${err.message}`);
      results.push({ index: i, filepath: null, prompt: item.prompt, success: false, error: err.message });
    }
  }
  return results;
}
